### ISSUE TITLE
Skript kann nicht kompiliert werden wegen fehlenden Bildern/PDF Ressourcen

### ISSUE THREAD

**Issue by dionysius** [AndreasFMueller/AutoSpr#21]
Ich musste folgende Zeilen auskommentieren um überhaupt kompilieren zu können:

Im `cfg.tex`:

        %\includegraphics{images/stack-1.pdf}
        %\includegraphics{images/stack-2.pdf}

Im `sudoku.tex`:

        %\includegraphics[width=0.5\hsize]{images/sudoku-1.pdf}

Diese Dateien fehlen tatsächlich im `images` Ordner.

Können diese noch nachgereicht werden?

**Comment by L4rS6** [comment]
Habe genau das selbe Problem...

**Comment by Darnor** [comment]
Gerade getestet. Kompilieren funktioniert nun ohne Probleme.

**Comment by dionysius** [comment]
confirm, klappt :)
